gText_Birch_Welcome:: @ 82C897B
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the Yorunashi Region!\p"
	.string "My name is Professor Lupine.\p"
	.string "Not to brag, but some say that I was\n"
	.string "once among the most prolific Pokémon\l"
	.string "researchers in the nation!\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "Speaking of which...\p"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "He's a trusted companion of mine!\n"
	.string "Pretty cute, isn't he?\p"
	.string "This world is widely inhabited by\n"
	.string "these creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "Maybe they will never be solved,\n"
	.string "and maybe some were never meant\l"
	.string "to be solved!\p"
	.string "Either way, many trainers seek out\n"
	.string "the truth behind these mysteries--\l"
	.string "whether in search of fame, fortune,\l"
	.string "power, or adventure.\p"
	.string "Will you be one of them?\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Incidentally, who are you?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "{COLOR 40}Who are you?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "{COLOR 40}What is your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "{COLOR 40}Is {PLAYER}{KUN} correct?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "{PLAYER}{KUN}!\p"
	.string "I know that name!\p"
	.string "You know, I've heard you're moving out\n"
	.string "this summer. Isn't that right?\p"
	.string "Hmmm...\p"
	.string "It's a big change, but I am sure\n"
	.string "you can handle it!\p"
	.string "Hopefully you can find a new place to\n"
	.string "stay before the Star Festival!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Alrighty then-- you ready?\p"
	.string "Oh, one more thing!\p"
	.string "If you ever find yourself in Ensio City,\n"
	.string "you should swing by my shop.\p"
	.string "I have something I want to ask of you.\p"
	.string "$"
