gText_Birch_Welcome:: @ 82C897B
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the Yorunashi Region!\p"
	.string "My name is Dr. Akileija.\p"
	.string "Hahah, don't worry, you can just call me\n"
	.string "Professor A.\p"
	.string "Not to brag, but some say that I'm among\n"
	.string "the most prolific Pokémon researchers\l"
	.string "in Yorunashi!\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "Speaking of which...\p"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "He's a trusted companion of mine!\n"
	.string "Pretty cute, isn't he?\p"
	.string "This world is widely inhabited by\n"
	.string "these creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "To unravel Pokémon mysteries,\n"
	.string "I, and many others, have been\l"
	.string "undertaking research on Pokémon.\p"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are...$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "{COLOR 40}Are you a boy or a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "{COLOR 40}Enter your name.$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "{COLOR 40}Is {PLAYER}{KUN} correct?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "{PLAYER}{KUN}!\p"
	.string "You know, I've heard you're moving out\n"
	.string "soon. Isn't that right?\p"
	.string "Hmm. It's a big change, but I am sure\n"
	.string "you can handle it!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Alrighty then-- you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Oh, one more thing!\p"
	.string "I have a lab in Ensio City, north of\n"
	.string "the Forest.\p"
	.string "You should stop by, I have something I\n"
	.string "want to ask of you.\p"
	.string "$"
